scheduler/config/routes.rb
Apify::Scheduler::Engine.routes.draw do
  root 'units#index'
  resources :units, :shallow => true do
    resources :histories, only: [:index, :destroy]
    member do
      post :perform
    end
  end
  resources :servers do
    member do
      post :test
    end
  end

end

scheduler/app/models/apify/scheduler/frequency_period.rb
module Apify::Scheduler
  class FrequencyPeriod < ActiveRecord::Base

  end
end

scheduler/app/models/apify/scheduler/history.rb
module Apify::Scheduler
  class History < ActiveRecord::Base
    belongs_to :unit, class_name: 'Apify::Scheduler::Unit', foreign_key: :apify_scheduler_unit_id

    def currently_working?
      Resque.working.map{ |w| w.job['payload']['args'].last }.include? self.id
    end
  end
end

scheduler/app/models/apify/scheduler/server.rb
module Apify::Scheduler
  class Server < ActiveRecord::Base
    validates :name, :url, :api_key, presence: true
    has_many :units, foreign_key: :apify_scheduler_server_id

    def test_api_key
      test_url = "#{url.chomp('/')}/test-api-key?apify_secret=#{api_key}"
      response = begin
        RestClient.post(test_url, {})
      rescue RestClient::ResourceNotFound => e
        { status: '0', message: e.message}.to_json
      end
      JSON.parse(response)
    end
  end
end

scheduler/app/models/apify/scheduler/unit.rb
module Apify::Scheduler
  class Unit < ActiveRecord::Base
    require 'rest_client'
    require 'pry'
    validates :name, :pattern, :destination, :server, presence: true
    belongs_to :server, class_name: 'Apify::Scheduler::Server', foreign_key: :apify_scheduler_server_id
    belongs_to :frequency_period, class_name: 'Apify::Scheduler::FrequencyPeriod', foreign_key: :apify_scheduler_frequency_period_id

    has_many :histories, foreign_key: :apify_scheduler_unit_id

    def currently_working?
      Resque.working.map{ |w| w.job['payload']['args'].first }.include? self.id
    end

    def enqueue
      history = histories.create
      Resque.enqueue(UnitPerformerJob, self.id, history.id)
    end

    def perform
      begin
        json = pattern
        server_query = ["processes=#{processes}", "delay=#{delay}", "apify_secret=#{server.api_key}"].join('&')
        server_crawler_url = [server.url.chomp('/'), '/crawler'].join
        server_url = [server_crawler_url, server_query].join('?')

        request_resource = RestClient::Resource.new( server_url, timeout: 90000, open_timeout: 90000 )
        request = request_resource.post json, {:content_type => :json, :accept => :json}

        # TODO: record download attempts
        # request = JSON.parse(request)

        response_resource = RestClient::Resource.new( destination, timeout: 90000, open_timeout: 90000 )
        response_resource.post request, {:content_type => :json, :accept => :json}
      #rescue ActiveRecord, JSON, RestClient, Parallel, Errno, Errno::EPIPE, Errno::PIPE
      rescue Exception => e
        { success: 0, message: "#{e.class}: #{e.message}"}.to_json
      end
    end

    def frequency
      frequency_quantity.send(frequency_period.name.pluralize)
    end
  end
end

scheduler/app/controllers/apify/scheduler/application_controller.rb
module Apify
  module Scheduler
    class ApplicationController < ActionController::Base
    end
  end
end

scheduler/app/controllers/apify/scheduler/histories_controller.rb
module Apify::Scheduler
  class HistoriesController < ApplicationController
    layout 'apify/scheduler/application'
    before_action :set_history, only: [:destroy]

    # GET /histories
    def index
      @unit = Unit.find(params[:unit_id])
      @histories = @unit.histories.order('created_at DESC')
    end

    # DELETE /histories/1
    def destroy
      @history.destroy
      redirect_to :back, notice: 'History was successfully destroyed.'
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_history
        @history = History.find(params[:id])
      end
  end
end

scheduler/app/controllers/apify/scheduler/servers_controller.rb
module Apify
  module Scheduler
    class ServersController < ApplicationController
      layout 'apify/scheduler/application'
      before_action :set_server, only: [:show, :edit, :update, :destroy, :test]

      # GET /servers
      def index
        @servers = Apify::Scheduler::Server.all
      end

      # GET /servers/1
      def show
      end

      # GET /servers/new
      def new
        @server = Apify::Scheduler::Server.new
      end

      # GET /servers/1/edit
      def edit
      end

      def test
        response  = @server.test_api_key
        message   = response['message']
        flash_key = response['status'] == '1' ? :notice : :error

        redirect_to servers_path, flash: { flash_key => message }
      end

      # POST /servers
      def create
        @server = Apify::Scheduler::Server.new(server_params)

        if @server.save
          redirect_to @server, notice: 'Server was successfully created.'
        else
          render :new
        end
      end

      # PATCH/PUT /servers/1
      def update
        if @server.update(server_params)
          redirect_to @server, notice: 'Server was successfully updated.'
        else
          render :edit
        end
      end

      # DELETE /servers/1
      def destroy
        @server.destroy
        redirect_to servers_url, notice: 'Server was successfully destroyed.'
      end

      private
        # Use callbacks to share common setup or constraints between actions.
        def set_server
          @server = Apify::Scheduler::Server.find(params[:id])
        end

        # Only allow a trusted parameter "white list" through.
        def server_params
          params.require(:server).permit(:name, :url, :description, :api_key)
        end
    end
  end
end

scheduler/app/controllers/apify/scheduler/units_controller.rb
module Apify
  module Scheduler
    class UnitsController < ApplicationController

      layout 'apify/scheduler/application'
      before_action :set_unit, only: [:show, :edit, :update, :destroy, :perform]


      # GET /units
      def index
        @units = Apify::Scheduler::Unit.all
      end

      # GET /units/1
      def show
      end

      # GET /units/new
      def new
        @unit = Apify::Scheduler::Unit.new
      end

      # GET /units/1/edit
      def edit
      end

      # POST /units
      def create
        @unit = Apify::Scheduler::Unit.new(unit_params)

        if @unit.save
          redirect_to @unit, notice: 'Unit was successfully created.'
        else
          render :new
        end
      end

      # PATCH/PUT /units/1
      def update
        if @unit.update(unit_params)
          redirect_to @unit, notice: 'Unit was successfully updated.'
        else
          render :edit
        end
      end

      # POST /units/1/perform
      def perform
        worker = @unit.enqueue
        message   = worker ? "Successfully added #{@unit.name} unit to queue. Refresh page to see progress." : "Error occured while queuing #{@unit.name}. Try again"
        flash_key = worker ? :notice : :error
        redirect_to units_path, flash: { flash_key => message }
      end

      # DELETE /units/1
      def destroy
        @unit.destroy
        redirect_to units_url, notice: 'Unit was successfully destroyed.'
      end

      private
        # Use callbacks to share common setup or constraints between actions.
        def set_unit
          @unit = Apify::Scheduler::Unit.find(params[:id])
        end

        # Only allow a trusted parameter "white list" through.
        def unit_params
          params.require(:unit).permit( :name, :description, :pattern,
                                        :processes, :delay, :destination,
                                        :apify_scheduler_server_id, :apify_scheduler_frequency_period_id,
                                        :frequency_quantity, :at)
        end

    end
  end
end

scheduler/app/helpers/apify/scheduler/application_helper.rb
module Apify
  module Scheduler
    module ApplicationHelper
    end
  end
end

scheduler/app/helpers/apify/scheduler/histories_helper.rb
module Apify::Scheduler
  module HistoriesHelper
  end
end

scheduler/app/helpers/apify/scheduler/servers_helper.rb
module Apify::Scheduler
  module ServersHelper
  end
end

scheduler/app/helpers/apify/scheduler/units_helper.rb
module Apify::Scheduler
  module UnitsHelper
  end
end

scheduler/app/views/apify/scheduler/histories/_history.html.erb
<div class='ui segment'>
  <div class='ui column right aligned'>
    <%= link_to raw('<i class="remove circle icon red"></i>'), history_path(history), method: :delete, 'data-confirm' => "Are you sure?" %>
  </div>
  <%= render 'apify/scheduler/shared/short_history', history: history %>
</div>

scheduler/app/views/apify/scheduler/histories/index.html.erb
<div class='ui grid'>
  <div class='ui column'>
    <div class='ui segment'>

      <h1 class='ui header'>
        <%= @unit.name %>
        Histories
      </h1>

      <%= render @histories %>

    </div>
  </div>
</div>

scheduler/app/views/apify/scheduler/servers/_form.html.erb
<div class='ui grid'>
  <div class='column'>
    <div class='ui segment form'>

      <%= form_for(@server) do |f| %>
        <% if @server.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@server.errors.count, "error") %> prohibited this server from being saved:</h2>

            <ul>
            <% @server.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>

        <div class="field">
          <div class='ui input'>
            <%= f.label :name %><br>
            <%= f.text_field :name %>
          </div>
        </div>
        <div class="field">
          <div class='ui input'>
            <%= f.label :url %><br>
            <%= f.text_field :url %>
          </div>
        </div>
        <div class="field">
          <div class='ui input'>
            <%= f.label :api_key %><br>
            <%= f.text_field :api_key %>
          </div>
        </div>
        <div class="field">
          <div class='ui input'>
            <%= f.label :description %><br>
            <%= f.text_area :description %>
          </div>
        </div>
        <div class="right aligned column">
          <%= f.submit (@server.persisted? ? 'Update Server' : 'Create Server'), class: 'ui blue submit button' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

scheduler/app/views/apify/scheduler/servers/edit.html.erb
<h1>Editing Server</h1>

<%= render 'form' %>

<%= link_to 'Show', @server %>
<%= link_to 'Back', servers_path %>

scheduler/app/views/apify/scheduler/servers/index.html.erb
<div class='ui sixteen wide column'>
  <% if @servers.present? %>

    <h1 class='ui header'>Servers</h1>
    <table class='ui celled stripped teal table'>
      <thead>
        <tr>
          <th>Name</th>
          <th>Info</th>
        </tr>
      </thead>

      <tbody>
        <% @servers.each do |server| %>
          <tr>
            <td>
              <div class='ui column right aligned'>
                <%= link_to raw('<i class="remove circle icon red"></i>'), server, method: :delete, data: { confirm: 'Are you sure?' } %>
                <%= link_to raw('<i class="configure icon"></i>'), edit_server_path(server) %>
                <%= link_to raw('<i class="video play icon green"></i>'), test_server_path(server), method: :post %>
              </div>
              <%= link_to server.name, server %>
            </td>
            <td>

              <b><%= server.url %></b>
              <br/>
              <small>
                <%= server.units.map.map(&:name).join("; ") %>
              </small>
            </td>

          </tr>
        <% end %>
      </tbody>
    </table>
  <% else %>
    <h1 class='ui header'>No servers present</h1>
    <p>Create your first.</p>

  <% end %>

  <div class='  right aligned column'>
    <%= link_to 'New Server', new_server_path, class: 'ui primary button ' %>
  </div>
</div>

scheduler/app/views/apify/scheduler/servers/new.html.erb
<h1>New Server</h1>

<%= render 'form' %>

<%= link_to 'Back', servers_path %>

scheduler/app/views/apify/scheduler/servers/show.html.erb
<div class='ui grid'>
  <div class='ui column'>
    <div class='ui segment'>

      <h1 class='ui header'><%= @server.name %></h1>

       <p class='ui segment stacked'>
        <%= @server.description %>
      </p>

      <p class='ui segment'>
        <%= @server.url %>
      </p>

      <h4>API key</h4>
      <p class='ui segment'>
        <%= @server.api_key %>
      </p>

      <h4>Units</h4>
      <p class='ui segment'>
        <%= @server.units.map(&:name).join(",") %>
      </p>

      <div class='ui column right aligned'>
        <%= link_to 'Edit', edit_server_path(@server), class: 'ui primary button' %>
        <%= link_to 'Test', test_server_path(@server), class: 'ui teal button', method: :post %>
        <%= link_to 'Back', servers_path, class: 'ui warning button' %>
      </div>

    </div>
  </div>
</div>

scheduler/app/views/apify/scheduler/shared/_short_history.html.erb
<% if history %>

  <% unless history.queued? %>
    Waiting to put on queue...
  <% end %>

  <% if history.finished_at.nil? and history.queued? and !history.currently_working? %>

    <div class='ui column center aligned red'>
      <h2 class=''>Error</h2>
    </div>

  <% end %>

  <% if history.finished_at or history.currently_working? %>

    <b>Started</b>:
    <%= history.created_at.strftime("%e %h, %X") %>
    <% if history.finished_at %>
      <br/>
      <b>Finished</b>:
      <%= history.finished_at.strftime("%e %h, %X")  %>
      <br/>
      <b>Time</b>: <%= (history.finished_at - history.created_at).round %> seconds
    <% end %>
    <% if history.response_body.present? and json = JSON.try(:parse, history.response_body) %>
      <br/>
      <b>Message</b>:
      <i class='ui column <%= "red" if json["success"] == 0 %>'><%= json['message'].html_safe %></i>
    <% elsif history.response_body.present? %>
      <br/>
      <b>Message</b>:
      <i><%= history.response_body %></i>
    <% end %>

  <% end %>


<% end %>

scheduler/app/views/apify/scheduler/units/_form.html.erb
<div class='ui grid'>
  <div class='column'>
    <div class='ui segment form'>
      <%= form_for(@unit) do |f| %>
        <% if @unit.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@unit.errors.count, "error") %> prohibited this unit from being saved:</h2>

            <ul>
            <% @unit.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>

        <div class='field'>
          <div class="ui input">
            <%= f.label :name %><br>
            <%= f.text_field :name %>
          </div>
        </div>
        <div class='field'>
          <div class='ui input'>
            <%= f.label :description %><br>
            <%= f.text_area :description %>
          </div>
        </div>
        <div class='field'>
          <div class='ui input'>
            <%= f.label :pattern %><br>
            <%= f.text_area :pattern %>
          </div>
        </div>
        <div class='field'>
          <div class='ui input'>
            <%= f.label :processes %><br>
            <%= f.text_field :processes %>
          </div>
        </div>
        <div class='field'>
          <div class='ui input'>
            <%= f.label :delay %><br>
            <%= f.text_field :delay %>
          </div>
        </div>
        <div class='field'>
          <div class='ui input'>
            <%= f.label :destination %><br>
            <%= f.text_field :destination %>
          </div>
        </div>

        <div class='field'>
          <div class='ui input'>
            <%= f.label :server %><br>
            <%= f.select :apify_scheduler_server_id, options_for_select(Apify::Scheduler::Server.all.map{ |s| [s.name, s.id]}, @unit.server.try(:id)) %>
          </div>
        </div>


        <h2>Clockwork Settings</h2>
        <div class='ui grid'>
          <div class='ui column one wide'>
          Every:
          </div>
          <div class='ui column four wide'>
            <div class='field'>
              <div class='ui input'>
                <%= f.number_field :frequency_quantity, placeholder: :quantity, required: true %>
              </div>
            </div>
          </div>
          <div class='ui column four wide'>
            <div class='field'>
              <div class='ui input'>
                <%= f.select :apify_scheduler_frequency_period_id, options_for_select(Apify::Scheduler::FrequencyPeriod.all.map{ |s| [s.name, s.id]}, @unit.frequency_period.try(:id)), required: true %>
              </div>
            </div>
          </div>
          <div class='ui column one wide'>at: </div>

          <div class='ui column four wide'>
            <div class='field'>
              <div class='ui input'>
                <%= f.text_field :at, placeholder: :optional %>
              </div>
            </div>
          </div>


          <div class="ui column sixteen wide right aligned">
            <%= f.submit (@unit.persisted? ? 'Update Unit' : 'Create Unit'), class: 'ui blue submit button' %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

scheduler/app/views/apify/scheduler/units/_unit.html.erb
<tr>
  <td>
    <div class='ui column right aligned'>
      <%= link_to raw('<i class="remove circle icon red"></i>'), unit, method: :delete, data: { confirm: 'Are you sure?' } %>
      <%= link_to raw('<i class="configure icon"></i>'), edit_unit_path(unit) %>
      <%= link_to raw('<i class="tasks icon"></i>'), unit_histories_path(unit) %>
      <%= link_to raw('<i class="video play icon green"></i>'), perform_unit_path(unit), method: :post if Resque.workers.present? %>
    </div>

    <% if unit.currently_working? %>
      <div class='ui inline active loader'></div>
    <% end %>

    <%= link_to unit.name, unit %>
    <br/>
    <b><sup>(Processes: <%= unit.processes %>, Delay: <%= unit.delay %>)</sup></b>
    <br/>
    <small>
      <i><%= unit.description %></i><br/>
      <b><%= unit.server.name %></b>:
      <b><%= unit.server.url %></b><br/>
    </small>
  </td>
  <td>
    <%= render 'apify/scheduler/shared/short_history', history: unit.histories.order('created_at DESC').first %>
  </td>
</tr>

scheduler/app/views/apify/scheduler/units/edit.html.erb
<h1 class='ui header'>Editing unit</h1>

<%= render 'form' %>

<%= link_to 'Show', @unit %> |
<%= link_to 'Back', units_path %>

scheduler/app/views/apify/scheduler/units/index.html.erb
  <div class='ui sixteen wide column'>

    <% unless Resque.workers.present? %>
      <div class="ui negative floating message">
        <i class="close icon"></i>
        <div class="header">Caution!</div>
        <p>
          Resque is disabled.
        </p>
      </div>
    <% end %>

  <% if @units.present? %>

    <h1 class='ui header'>Units</h1>
    <table class='ui celled stripped teal table'>
      <thead>
        <tr>
          <th>Name</th>
          <th>History</th>
        </tr>
      </thead>

      <tbody>
        <%= render @units %>
      </tbody>
    </table>
  <% else %>
    <h1 class='ui header'>No units present</h1>
    <p>Create your first.</p>

  <% end %>

  <div class='  right aligned column'>
    <%= link_to 'New Unit', new_unit_path, class: 'ui primary button ' %>
  </div>
</div>

scheduler/app/views/apify/scheduler/units/new.html.erb
<h1 class='ui header'>New unit</h1>

<%= render 'form' %>

<%= link_to 'Back', units_path %>

scheduler/app/views/apify/scheduler/units/show.html.erb
<div class='ui grid'>
  <div class='ui column'>
    <div class='ui segment'>

      <h1 class='ui header'>
        <%= @unit.name %>

      </h1>

      <p class='ui segment stacked'>
        <%= @unit.description %>
        <br/>
        <small>(
          <%=
          "In #{@unit.processes} processes with #{@unit.delay} milliseconds delay <i>to <b>#{@unit.destination}</b></i>".html_safe %>
        )</small>
      </p>

      <pre class='ui segment'><%= @unit.pattern.strip %></pre>

      <p class='ui segment'>
        <%= @unit.server.name %>
        <small><i>(<%= @unit.server.url %>)</i></small>
      </p>

      <div class='right aligned column'>
        <%= link_to 'Edit', edit_unit_path(@unit), class: 'ui primary button' %>
        <%= link_to 'Histories', unit_histories_path(@unit), class: 'ui primary button' %>
        <%= link_to 'Perform', perform_unit_path(@unit), class: 'ui teal button', method: :post %>
        <%= link_to 'Back', units_path, class: 'ui warning button' %>
      </div>
    </div>
  </div>
</div>

scheduler/app/views/layouts/apify/scheduler/_flash.html.erb
<div class="ui grid page">
  <div class="ui column four wide"></div>
  <div class="ui column seven wide">
    <% if flash[:error] %>
      <div class="ui negative floating message">
        <i class="close icon"></i>
        <div class="header">Error</div>
        <p>
          <%= flash[:error] %>
        </p>
      </div>
    <% end %>
    <% if flash[:notice] %>
      <div class="ui positive floating message">
        <i class="close icon"></i>
        <div class="header">Note</div>
        <p>
          <%= flash[:notice] %>
        </p>
      </div>
    <% end %>
    <% if flash[:alert] %>
      <div class="ui warning floating message">
        <i class="close icon"></i>
        <div class="header">Warning</div>
        <p>
          <%= flash[:alert] %>
        </p>
      </div>
    <% end %>
  </div>
</div>

scheduler/app/views/layouts/apify/scheduler/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Scheduler</title>
  <%= stylesheet_link_tag    "scheduler/application", media: "all" %>
  <%= stylesheet_link_tag    "https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/1.5.2/semantic.min.css", media: "all" %>


  <%= csrf_meta_tags %>
</head>
<body>
  <div class='ui inverted menu'>
    <div class='item'><%= link_to 'Apify Scheduler', root_path %></div>
    <div class='item'><%= link_to 'Units', units_path %></div>
    <div class='item'><%= link_to 'Servers', servers_path %></div>
    <% if defined?(current_user) and current_user.present? %>
      <div class='item'><%= link_to 'Logout', main_app.destroy_user_session_path, method: :delete %></div>
    <% elsif defined?(current_user) %>
      <div class='item'><%= link_to 'Login', main_app.new_user_session_path, method: :post %></div>
    <% end %>
  </div>

  <%= render 'layouts/apify/scheduler/flash' %>

  <div class='ui page grid'>
    <div class='main container'>
      <div class='ui grid full'>
        <div class='sixteen column row'>
          <%= yield %>
        </div>
      </div>
    </div>
  </div>

  <%= javascript_include_tag "scheduler/application" %>
</body>
</html>